### PR TITLE
Registeraccount

### PR DESCRIPTION
**Pull request by ringaile**
Implemented fronted and backend.

### CODE REVIEW

**Comment by ringaile** [comment]
Screen Shot 2019-07-02 at 00 28 08

**Comment by ajmachado** [comment]
I think we need a text box for the initial funding amount.

**Comment by ringaile** [comment]
ok, i will add it.

Just a question. the initial amount will be used later for challenging articles (as a stake), right?

**Comment by ajmachado** [comment]
Yes. We will check the balance before staking. Also, the Validator and Contributor will always need to have a minimum balance.

**Comment by ringaile** [comment]
Screen Shot 2019-07-02 at 19 31 18

**Comment by ajmachado** [comment]
Changes look good.

**Comment by ajmachado** [comment]
The index.html is missing the html code for 'add article'. Can you add that and then merge this PR. I cannot test the Add Article without the registration.

**Comment by ringaile** [comment]
done.

**Pull request merged**
