### PR TITLE
Voting

### PR DESCRIPTION
**Pull request by ringaile**
connected frontend html with solidity to add upvotes and downvotes.
Buttons were already implemented
and contract functions were already implemented too

### CODE REVIEW

**Comment by ringaile** [comment]
you mean this one, right?

> updateContributorRating(bool vote, bool challengeLost, address _contributor, uint articleId)

sure, and what should i put for bool vote? 
what is it for? :)

**Comment by ajmachado** [comment]
Yes. True for upvotes. False for downvote.

**Comment by ringaile** [comment]
updated the function, i used updateValidatorRanking function from main contract

**Comment by ajmachado** [comment]
You need to use the updateContributorRanking function instead of the updateValidatorRaking function, because voting affects the Contributor's ranking. :)

**Comment by ringaile** [comment]
updated

**Pull request merged**
