### PR TITLE
created Readme from our word document

### PR DESCRIPTION
**Pull request by ringaile**
You can see how it looks directly here:
https://github.com/ringaile/honest_media/blob/readme/README.md

used styling from here:
https://help.github.com/en/articles/basic-writing-and-formatting-syntax#lists

### CODE REVIEW

**Comment by ajmachado** [comment]
I changed the test for the functionality issues section.
Functionality Issues:
We had trouble retrieving the files uploaded to IPFS. Adding files to IPFS does not result in any errors, but trying to access the file on IPFS using the hash, results in a timeout. We were successful in adding and retrieving smaller sized text and image files.

**Comment by ringaile** [comment]
updated

**Comment by ajmachado** [comment]
on discord "Please ensure your teammates Github handles are included in your final submission! Happy final hacking + let us know if you have any questions". Maybe we should add our github profiles in the developer's section as well.  Mine is https://github.com/ajmachado

**Comment by ringaile** [comment]
updated

**Pull request merged**
