### PR TITLE
feat: added Article Contract

### PR DESCRIPTION
**Pull request by ajmachado**
Take a look and let me know if this contract will work. I have not used Roles.

### CODE REVIEW

**Comment by ringaile** [comment]
I think it was a good idea to have a separate contract for articles. 
I am not sure if articles need an address, but i really like that the code for handling articles is separated from the code of contributors.

But i think each contributor should have a mapping of his articles inside his struct.
So maybe contributor struct should have a mapping of articles

**Comment by ringaile** [comment]
looks good! 

do you think we need to also add addarticle function in main contract?
so we can also add a modifier that allows only contributors to add an article

**Comment by ajmachado** [comment]
> looks good!
> 
> do you think we need to also add addarticle function in main contract?
> so we can also add a modifier that allows only contributors to add an article

Yes. I will add the modifier for challenges in the reader role as well.

**Comment by ringaile** [comment]
Super!

Also I think we need addarticle function in main contract that will be used in front end!

**Comment by ajmachado** [comment]
Is it ok to merge this?

**Comment by ringaile** [comment]
If a function to add article is already in main contract. I think yes :)

**Comment by ajmachado** [comment]
Added the add article function, but it is not fully implemented. The part of assigning validators needs to be completed.

**Comment by ringaile** [comment]
Ok. Thank you! Looks good

**Pull request merged**
