### PR TITLE
added updateranking js function

### PR DESCRIPTION
**Pull request by ringaile**
just implemented the function in a fronted
(backend was implemented by you).

I did not add anything in html,
because I though, this function will be called automatically once three validators validate the article.

### CODE REVIEW

**Comment by ringaile** [comment]
ok, so just to get the idea, we update ranking after upvotes and downvotes, right?

and ranking is not changed based on any other criteria?

I think i got a bit confused.
in that case, i will fix #31 and this is not relevant for us

**Comment by ajmachado** [comment]
The contributor will lose one ranking point if he loses a challenge.

Sent from Mail for Windows 10

**Comment by ringaile** [comment]
ok, so i can close this pull request? :)

**Comment by ajmachado** [comment]
Yes

**Pull request closed without merging**
