### PR TITLE
feat: Added Withdraw and fallback functions

### PR DESCRIPTION
**Pull request by ajmachado**

### CODE REVIEW

**Comment by ringaile** [comment]
looks good!

just a question, why did you rename the function

> addArticle

to 

> add

 ?

**Comment by ajmachado** [comment]
I was testing the add article function from the frontend and kept giving me an error for number of arguments do not match. Since both contracts had a function with the same name, I thought it would make it easier to rename one to ‘add’.

Sent from Mail for Windows 10

**Comment by ajmachado** [comment]
I don't know how to solve the merge conflict on this. Can you help?

**Comment by ringaile** [comment]
just did it. it should be all ok now

**Comment by ajmachado** [comment]
Thanks! How did you do it?

**Comment by ringaile** [comment]
first of all i made sure i have a latest master
git checkout master
git pull

then I checked out your branch
git checkout ajmachado:master

then i merge:
git merge master

then i have to manually fix all merge conflicts
then
git add .
git commit
git push

**Pull request merged**
